# .github/workflows/ci.yml
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Ubuntu with MySQL
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: "YAPM_TEST2"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_NAME: "YAPM_TEST2"
      DATABASE_BASE_URL: "jdbc:mysql://127.0.0.1:3306/"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: ""
      MASTER_USER_TABLE: "master_users"
      JDBC_URL: "jdbc:mysql://127.0.0.1:3306/YAPM_TEST2"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            mysql -h127.0.0.1 -uroot -e "SELECT 1" >/dev/null 2>&1 && break
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Build and run tests
        run: ./gradlew build --no-daemon

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-ubuntu
          path: |
            **/build/test-results/test
            **/app/build/test-results/test

  build-macos:
    name: Build on macOS (no MySQL service)
    runs-on: macos-latest
    env:
      # if tests depend on DB, you may skip or use alternative config here
      SKIP_DB_TESTS: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew build --no-daemon

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-macos
          path: |
            **/build/test-results/test
            **/app/build/test-results/test

  build-windows:
    name: Build on Windows (no MySQL service)
    runs-on: windows-latest
    env:
      SKIP_DB_TESTS: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build and run tests
        run: .\gradlew.bat build --no-daemon

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-windows
          path: |
            **/build/test-results/test
            **/app/build/test-results/test
